### ISSUE TITLE
guid.HasValue and IsEmpty producing code warnings for null 

### ISSUE THREAD

**Issue by suman-carsales** [mruhul/Bolt.Common.Extensions#5]
If(nullableGuidObject.HasValue())
{
// Here  do not expect nullableGuidObject to be null anymore. But seems there is still code warnings coming along 
}

Same with IsEmpty method.

**Comment by mruhul** [comment]
Not all methods are migrated based on nullable feature of .net. Feel free to raise a PR if you have time otherwise I will do the change when I have some time fix. Thanks for checking and raising the issue :)
